/* eslint-disable @typescript-eslint/no-explicit-any */
import { ItineraryStop } from "@/types/itinerary";

export const MOCK_ITINERARY = {
  id: 999,
  title: "The Ultimate North Wales Weekend",
  slug: "ultimate-north-wales-weekend",
  tagline: "Mountains, Castles and Coast in 3 Action-Packed Days",
  description: "Experience the best of Snowdonia with this thrill-seeker weekend guide.",
  durationDays: 3,
  difficulty: "moderate",
  regionId: 1,
  priceEstimateFrom: "350.00",
  priceEstimateTo: "600.00",
  heroImage: null,
  bestSeason: "Spring/Summer",
  status: "published",
  region: {
      name: "Snowdonia",
      slug: "snowdonia"
  }
};

export const MOCK_STOPS: ItineraryStop[] = [
    {
        id: 1,
        itineraryId: 999,
        dayNumber: 1,
        orderIndex: 1,
        stopType: 'activity',
        title: 'The Fastest Zip Line in the World',
        description: 'Experience Velocity 2, soaring over Penrhyn Quarry.',
        startTime: '10:00',
        duration: '2 hours',
        travelToNext: '30 min drive',
        travelMode: 'drive',
        lat: "53.17",
        lng: "-4.06",
        wetAltTitle: 'Explore the Slate Caverns',
        wetAltDescription: 'Go underground to escape the rain.',
        wetAltActivity: { lat: "52.99", lng: "-3.94", name: 'Slate Caverns' } as any,
        budgetAltTitle: 'Walk around Padarn Lake',
        budgetAltDescription: 'Enjoy the scenic views for free.',
        budgetAltActivity: { lat: "53.11", lng: "-4.11", name: 'Padarn Lake Walk' } as any,
        costFrom: "89.00",
    } as any,
    {
        id: 2,
        itineraryId: 999,
        dayNumber: 1,
        orderIndex: 2,
        stopType: 'food',
        title: 'Lunch at The Slate',
        description: 'Great local food right by the quarry.',
        startTime: '12:30',
        duration: '1 hour',
        travelToNext: '15 min drive',
        lat: "53.17",
        lng: "-4.06",
        costFrom: "15.00",
    } as any,
    {
        id: 3,
        itineraryId: 999,
        dayNumber: 2,
        orderIndex: 1,
        stopType: 'activity',
        title: 'Conquer Mount Snowdon',
        description: 'Take the Pyg Track up to the summit. A challenging but rewarding hike offering the best views in Wales.',
        startTime: '09:00',
        duration: '6 hours',
        lat: "53.06",
        lng: "-4.07",
        wetAltTitle: 'Visit Conwy Castle',
        wetAltDescription: 'Stay dry inside a medieval fortress and explore the historic town walls.',
        wetAltActivity: { lat: "53.28", lng: "-3.83", name: 'Conwy Castle' } as any,
        costFrom: "0.00",
    } as any,
];
