#!/usr/bin/env python3
"""
Adventure Wales daily Jules research campaign runner.

Purpose:
- Read the live content-ops queue (content/ops/task-queue.json) and launch
  research-only Jules sessions for tasks that are actually eligible for
  research right now.
- Never invent a task bank: task identity, briefs, acceptance criteria and
  source requirements all come from the queue, which is regenerated by
  `npm run content-ops:audit`.
- Each launched session is bounded to producing a single research/proposal
  JSON file. It must never touch application code, tests, migrations,
  scripts, CI/config, deployment, database, email or publishing.

State lives outside the repo at ~/.hermes/state/adventure-wales-jules-campaign.json.
A task (identified by its content_item_id + a fingerprint of its material
fields) is only launched once per fingerprint. If the queue task changes
materially (new brief, new status, etc.) it gets a new fingerprint and
becomes eligible again — this replaces the old permanently-consumed
`submitted_keys` list, which could exhaust itself forever against a fixed
task bank. Historical launch records are never deleted.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

REPO_ROOT = Path(__file__).resolve().parents[2]
QUEUE_PATH = REPO_ROOT / "content" / "ops" / "task-queue.json"
STATE_PATH = Path.home() / ".hermes" / "state" / "adventure-wales-jules-campaign.json"

JULES_API_BASE = "https://jules.googleapis.com/v1alpha"
JULES_SOURCE = "sources/github/mk-162/Adventure-Site"
JULES_REPO_LABEL = "mk-162/Adventure-Site"

DEFAULT_DAILY_LIMIT = 100
RESEARCH_ELIGIBLE_STATUSES = {"research_needed", "refresh_due"}

REQUIRED_STR_FIELDS = (
    "id",
    "content_item_id",
    "channel",
    "content_type",
    "route_or_slug",
    "title",
    "status",
    "recommended_skill",
    "task_type",
    "brief",
    "output_path",
)
REQUIRED_LIST_FIELDS = ("acceptance_criteria", "source_requirements")

FINGERPRINT_FIELDS = (
    "content_item_id",
    "channel",
    "content_type",
    "route_or_slug",
    "title",
    "status",
    "task_type",
    "brief",
    "acceptance_criteria",
    "source_requirements",
    "output_path",
)


class JulesApiError(Exception):
    """Raised for any failure talking to the Jules API. Never carries the API key."""

    def __init__(self, message: str, status_code: int | None = None):
        super().__init__(message)
        self.status_code = status_code


# ---------------------------------------------------------------------------
# Queue loading & validation
# ---------------------------------------------------------------------------


def validate_task(task: object) -> bool:
    if not isinstance(task, dict):
        return False
    for field in REQUIRED_STR_FIELDS:
        value = task.get(field)
        if not isinstance(value, str) or not value:
            return False
    for field in REQUIRED_LIST_FIELDS:
        if not isinstance(task.get(field), list):
            return False
    priority = task.get("priority")
    if isinstance(priority, bool) or not isinstance(priority, (int, float)):
        return False
    return True


def load_queue(path: Path) -> tuple[list[dict], int, str | None]:
    """Returns (valid_tasks, invalid_task_count, fatal_error).

    fatal_error is set only when the queue file itself is unreadable/malformed;
    individual malformed task entries are skipped and counted instead.
    """
    if not path.exists():
        return [], 0, f"queue file not found: {path}"
    try:
        raw_text = path.read_text(encoding="utf-8")
    except OSError as exc:
        return [], 0, f"could not read queue file: {exc}"
    try:
        data = json.loads(raw_text)
    except json.JSONDecodeError as exc:
        return [], 0, f"queue file is not valid JSON: {exc}"
    if not isinstance(data, dict) or not isinstance(data.get("tasks"), list):
        return [], 0, "queue file is missing a 'tasks' array"

    valid: list[dict] = []
    invalid_count = 0
    for entry in data["tasks"]:
        if validate_task(entry):
            valid.append(entry)
        else:
            invalid_count += 1
    return valid, invalid_count, None


# ---------------------------------------------------------------------------
# Selection
# ---------------------------------------------------------------------------


def _priority(task: dict) -> float:
    value = task.get("priority", 0)
    return float(value) if isinstance(value, (int, float)) and not isinstance(value, bool) else 0.0


def select_research_tasks(tasks: list[dict]) -> list[dict]:
    """Research-eligible tasks, sorted deterministically by priority desc then id asc."""
    eligible = [
        t
        for t in tasks
        if t.get("task_type") == "research" and t.get("status") in RESEARCH_ELIGIBLE_STATUSES
    ]
    eligible.sort(key=lambda t: (-_priority(t), str(t.get("id", ""))))
    return eligible


def task_fingerprint(task: dict) -> str:
    """Hash of the task's material fields. Changes whenever the task content changes."""
    material = {field: task.get(field) for field in FINGERPRINT_FIELDS}
    canonical = json.dumps(material, sort_keys=True, ensure_ascii=False)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def is_already_launched(state: dict, content_item_id: str, fingerprint: str) -> bool:
    records = state.get("launch_records", {}).get(content_item_id, {}).get("records", [])
    return any(r.get("fingerprint") == fingerprint and r.get("status") == "submitted" for r in records)


def partition_by_launch_state(
    tasks: list[dict], state: dict, limit: int
) -> tuple[list[dict], list[dict]]:
    """Splits research-eligible tasks into (selected, already_launched_skipped).

    `selected` respects `limit` and only contains tasks not already launched
    at their current fingerprint. `already_launched_skipped` is unbounded
    (used for reporting, not counted against the limit).
    """
    selected: list[dict] = []
    skipped: list[dict] = []
    for task in tasks:
        fingerprint = task_fingerprint(task)
        if is_already_launched(state, task.get("content_item_id"), fingerprint):
            skipped.append(task)
            continue
        if len(selected) < limit:
            selected.append(task)
    return selected, skipped


# ---------------------------------------------------------------------------
# State (durable launch records)
# ---------------------------------------------------------------------------


def load_state(path: Path) -> dict:
    if path.exists():
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            data = None
        if isinstance(data, dict):
            data.setdefault("runs", {})
            data.setdefault("launch_records", {})
            return data
    return {"runs": {}, "launch_records": {}}


def save_state(path: Path, state: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(state, indent=2, ensure_ascii=False), encoding="utf-8")


def next_attempt_number(state: dict, content_item_id: str) -> int:
    records = state.get("launch_records", {}).get(content_item_id, {}).get("records", [])
    return len(records) + 1


def record_launch(state: dict, content_item_id: str, record: dict) -> None:
    entry = state.setdefault("launch_records", {}).setdefault(content_item_id, {"records": []})
    entry["records"].append(record)


# ---------------------------------------------------------------------------
# Research-only brief
# ---------------------------------------------------------------------------


def build_session_title(task: dict) -> str:
    return f"[Adventure Wales Research] {task.get('content_item_id', 'unknown')}"[:200]


def build_research_brief(task: dict) -> str:
    acceptance = "\n".join(f"- {item}" for item in task.get("acceptance_criteria", []))
    sources = "\n".join(f"- {item}" for item in task.get("source_requirements", []))
    return f"""# Adventure Wales — Jules Research Task

Repo: {JULES_REPO_LABEL}
Source: {JULES_SOURCE}
Queue task ID: {task.get('id')}
Content item: {task.get('content_item_id')}
Target route: {task.get('route_or_slug')}
Content type: {task.get('content_type')} ({task.get('channel')})
Required output file: {task.get('output_path')}

## Brief
{task.get('brief')}

## Scope: RESEARCH ONLY — read carefully
This is a research and proposal task. Do NOT:
- write or modify any application code, tests, database migrations, scripts, CI/CD, or configuration files
- deploy, publish, merge, or make any production or database change
- send email or perform any outbound/publishing action
- generate or use AI-generated imagery for real places, operators, or events
- use any image without a clear, checkable licence and attribution
- guess facts, prices, dates, safety claims, ratings, or contact details — including inferring them from seed CSV data without independent verification
- copy marketing copy verbatim from any source

You may ONLY create or update a single research/proposal JSON file, at exactly this path:
{task.get('output_path')}

## Acceptance criteria
{acceptance}

## Source requirements
{sources}

## Required output content
- Cite a source URL for every factual claim.
- Mark anything unverifiable as `needs_verification` instead of guessing.
- Recommend — do not perform — the next status for this item (e.g. researched, qa_needed, reviewed, blocked, or signed_off).

Do not take any action beyond producing this one research file.
"""


# ---------------------------------------------------------------------------
# Jules API
# ---------------------------------------------------------------------------


def create_session(api_key: str, prompt: str, title: str, timeout: int = 60) -> dict:
    """POST a new research session to the Jules API. Never logs the API key."""
    url = f"{JULES_API_BASE}/sessions"
    body = json.dumps(
        {
            "prompt": prompt,
            "title": title,
            "sourceContext": {
                "source": JULES_SOURCE,
                "githubRepoContext": {"startingBranch": "main"},
            },
        }
    ).encode("utf-8")
    request = Request(
        url,
        data=body,
        method="POST",
        headers={
            "Content-Type": "application/json",
            "X-Goog-Api-Key": api_key,
        },
    )
    try:
        with urlopen(request, timeout=timeout) as response:
            raw = response.read().decode("utf-8")
    except HTTPError as exc:
        detail = ""
        try:
            detail = exc.read().decode("utf-8", errors="replace")
        except Exception:
            pass
        raise JulesApiError(f"Jules API returned HTTP {exc.code}: {detail[:500]}", status_code=exc.code) from None
    except URLError as exc:
        raise JulesApiError(f"Jules API request failed: {exc.reason}") from None

    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError:
        raise JulesApiError("Jules API returned a non-JSON response") from None
    if not isinstance(parsed, dict):
        raise JulesApiError("Jules API returned an unexpected response shape")
    return parsed


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Adventure Wales research-only Jules campaign runner.")
    parser.add_argument("--limit", type=int, default=DEFAULT_DAILY_LIMIT, help="Maximum research sessions to launch this run.")
    parser.add_argument("--dry-run", action="store_true", help="Select and print tasks; make no network calls and write no state.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    today = dt.date.today().isoformat()

    valid_tasks, invalid_count, queue_error = load_queue(QUEUE_PATH)
    if queue_error:
        print(f"ERROR: {queue_error}")
        return 1

    state = load_state(STATE_PATH)
    research_tasks = select_research_tasks(valid_tasks)
    selected, skipped = partition_by_launch_state(research_tasks, state, args.limit)

    print(f"Adventure Wales Jules research campaign — {today}")
    invalid_note = f", {invalid_count} invalid/skipped" if invalid_count else ""
    print(
        f"Queue tasks: {len(valid_tasks)} valid{invalid_note}; "
        f"research-eligible: {len(research_tasks)}; "
        f"already launched (unchanged): {len(skipped)}; "
        f"selected: {len(selected)}; limit: {args.limit}"
    )

    if args.dry_run:
        if not selected:
            print("[DRY RUN] No eligible research tasks to launch.")
        else:
            print(f"[DRY RUN] Would launch {len(selected)} research session(s):")
            for task in selected:
                print(f"  - {task['id']} ({task['content_item_id']}) -> {task['output_path']}")
        return 0

    run_record = {
        "started_at": dt.datetime.now().isoformat(timespec="seconds"),
        "finished_at": None,
        "limit": args.limit,
        "queue_valid_tasks": len(valid_tasks),
        "queue_invalid_tasks": invalid_count,
        "research_eligible_count": len(research_tasks),
        "already_launched_skipped": [
            {"content_item_id": t.get("content_item_id"), "queue_task_id": t.get("id")} for t in skipped
        ],
        "selected": [t.get("id") for t in selected],
        "submitted": [],
        "failed": [],
    }

    if not selected:
        print("No eligible research tasks to launch.")
        run_record["finished_at"] = dt.datetime.now().isoformat(timespec="seconds")
        state["runs"][today] = run_record
        save_state(STATE_PATH, state)
        return 0

    api_key = os.environ.get("JULES_API_KEY", "").strip()
    if not api_key:
        print("ERROR: JULES_API_KEY is not set (or empty). Refusing to submit Jules sessions.")
        run_record["finished_at"] = dt.datetime.now().isoformat(timespec="seconds")
        run_record["error"] = "missing_api_key"
        state["runs"][today] = run_record
        save_state(STATE_PATH, state)
        return 1

    for idx, task in enumerate(selected, start=1):
        content_item_id = task.get("content_item_id")
        print(f"[{idx}/{len(selected)}] {task.get('id')} ({content_item_id})")
        fingerprint = task_fingerprint(task)
        attempt = next_attempt_number(state, content_item_id)
        at = dt.datetime.now().isoformat(timespec="seconds")
        try:
            response = create_session(api_key, build_research_brief(task), build_session_title(task))
        except Exception as exc:  # convert any failure into a recorded, non-fatal result
            error_message = str(exc)[:500]
            record_launch(
                state,
                content_item_id,
                {
                    "fingerprint": fingerprint,
                    "queue_task_id": task.get("id"),
                    "date": today,
                    "attempt": attempt,
                    "session_id": None,
                    "status": "failed",
                    "at": at,
                    "error": error_message,
                },
            )
            run_record["failed"].append(
                {"content_item_id": content_item_id, "queue_task_id": task.get("id"), "error": error_message}
            )
            print(f"  FAILED: {error_message}")
        else:
            session_id = response.get("name")
            record_launch(
                state,
                content_item_id,
                {
                    "fingerprint": fingerprint,
                    "queue_task_id": task.get("id"),
                    "date": today,
                    "attempt": attempt,
                    "session_id": session_id,
                    "status": "submitted",
                    "at": at,
                    "error": None,
                },
            )
            run_record["submitted"].append(
                {"content_item_id": content_item_id, "queue_task_id": task.get("id"), "session_id": session_id}
            )
            print(f"  OK -> session {session_id}")

        run_record["finished_at"] = dt.datetime.now().isoformat(timespec="seconds")
        state["runs"][today] = run_record
        save_state(STATE_PATH, state)

    print(f"Done. Submitted {len(run_record['submitted'])}, failed {len(run_record['failed'])}, of {len(selected)} selected.")
    print(f"State: {STATE_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
